// filename: src/components/BurgerStack.tsx
// Code Generated by Sidekick is for learning and experimentation purposes only.

import Ingredient from './Ingredient';
import type { Ingredient as IngredientType } from '../shared.types';

type BurgerStackProps = {
  stack: IngredientType[];
  onRemove: (index: number) => void;
};

const BurgerStack = ({
  stack,
  onRemove,
}: BurgerStackProps) => {
  return (
    <div>
      <h2>Your Burger</h2>

      <ul>
        {stack.length === 0 ? (
          <li>No Ingredients</li>
        ) : (
          stack.map((ingredient, index) => (
            <Ingredient
              key={`${ingredient.name}-${index}`}
              ingredient={ingredient}
              action="remove"
              onAction={() => onRemove(index)}
            />
          ))
        )}
      </ul>
    </div>
  );
};

export default BurgerStack;
