// filename: src/components/IngredientList.tsx
// Code Generated by Sidekick is for learning and experimentation purposes only.

import Ingredient from './Ingredient';
import type { Ingredient as IngredientType } from '../shared.types';

type IngredientListProps = {
  ingredients: IngredientType[];
  onAdd: (ingredient: IngredientType) => void;
};

const IngredientList = ({
  ingredients,
  onAdd,
}: IngredientListProps) => {
  return (
    <div>
      <h2>Ingredients</h2>

      <ul>
        {ingredients.map((ingredient) => (
          <Ingredient
            key={ingredient.name}
            ingredient={ingredient}
            action="add"
            onAction={() => onAdd(ingredient)}
          />
        ))}
      </ul>
    </div>
  );
};

export default IngredientList;
