// filename: src/components/Ingredient.tsx
// Code Generated by Sidekick is for learning and experimentation purposes only.

import type { Ingredient as IngredientType } from '../shared.types';

type IngredientProps = {
  ingredient: IngredientType;
  action: 'add' | 'remove';
  onAction: () => void;
};

const Ingredient = ({
  ingredient,
  action,
  onAction,
}: IngredientProps) => {
  const buttonLabel = action === 'add' ? '+' : 'X';

  return (
    <li
      className="ingredient"
      style={{ backgroundColor: ingredient.color }}
    >
      <span>{ingredient.name}</span>

      <button
        type="button"
        aria-label={`${action} ${ingredient.name}`}
        onClick={onAction}
      >
        {buttonLabel}
      </button>
    </li>
  );
};

export default Ingredient;
