// filename: src/App.tsx
// Code Generated by Sidekick is for learning and experimentation purposes only.

import { useState } from 'react';
import './App.css';
import BurgerStack from './components/BurgerStack';
import IngredientList from './components/IngredientList';
import type { Ingredient } from './shared.types';

export const availableIngredients: Ingredient[] = [
  { name: 'Kaiser Bun', color: 'saddlebrown' },
  { name: 'Sesame Bun', color: 'sandybrown' },
  { name: 'Gluten Free Bun', color: 'peru' },
  { name: 'Lettuce Wrap', color: 'olivedrab' },
  { name: 'Beef Patty', color: '#3F250B' },
  { name: 'Soy Patty', color: '#3F250B' },
  { name: 'Black Bean Patty', color: '#3F250B' },
  { name: 'Chicken Patty', color: 'burlywood' },
  { name: 'Lettuce', color: 'lawngreen' },
  { name: 'Tomato', color: 'tomato' },
  { name: 'Bacon', color: 'maroon' },
  { name: 'Onion', color: 'lightyellow' },
  { name: 'Cheddar Cheese', color: '#FDE18B' },
  { name: 'Swiss Cheese', color: '#F1E1A8' },
];

const App = () => {
  const [stack, setStack] = useState<Ingredient[]>([]);

  const addToStack = (ingredient: Ingredient) => {
    setStack((currentStack) => [...currentStack, ingredient]);
  };

  const removeFromStack = (indexToRemove: number) => {
    setStack((currentStack) =>
      currentStack.filter((_, index) => index !== indexToRemove),
    );
  };

  return (
    <main>
      <h1>Burger Stacker</h1>

      <section>
        <IngredientList
          ingredients={availableIngredients}
          onAdd={addToStack}
        />

        <BurgerStack
          stack={stack}
          onRemove={removeFromStack}
        />
      </section>
    </main>
  );
};

export default App;
